"""fix update users table

Revision ID: fe2b48738a8c
Revises: 0bba41a1ccd1
Create Date: 2024-06-02 16:03:40.803227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe2b48738a8c'
down_revision: Union[str, None] = '0bba41a1ccd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dieary_entries', 'last_modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'last_modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('dieary_entries', 'last_modified_on',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
